### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by shraggy**
Presentation and demo, might be good to include.

### CODE REVIEW

**Comment by cgmcintyr** [comment]
Yes, it would be good to include these.

However, I would include the powerpoint as a pdf rather than a powerpoint so it is viewable on github, and move both into the `examples/mbqc/docs` directory to reduce cluttering the main directory - what do you think?

**Comment by shraggy** [comment]
works!

**Comment by cgmcintyr** [comment]
Cool, would you like to make the changes on your branch and I can approve the pull request?

**Comment by cgmcintyr** [comment]
Otherwise I don't mind making the changes :)

**Comment by shraggy** [comment]
I can do that. :)

**Pull request closed without merging**
